version: '3.8'

services:
  # percona:
  #   image: percona:latest
  #   container_name: hw9-percona
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: test_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - hw9-percona_data:/var/lib/mysql

  mysql:
    image: mysql:latest
    container_name: hw9-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - hw9-mysql_data:/var/lib/mysql

volumes:
  # hw9-percona_data:
  hw9-mysql_data: