SET GLOBAL SQL_SLAVE_SKIP_COUNTER = 1;

CHANGE MASTER TO
MASTER_HOST='mysql-m',
MASTER_USER='replicator',
MASTER_PASSWORD='replica_pass',
MASTER_LOG_FILE='mysql-bin.000001',
MASTER_LOG_POS=0;

START SLAVE;
