# name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Change directory
        working-directory: hw23-cicd
        run: pwd

      - name: Install dependencies
        working-directory: hw23-cicd
        run: npm install
      
      - name: Run tests
        working-directory: hw23-cicd
        run: npm run test

#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Zip Lambda package
#         run: zip -r lambda-package.zip .

#       - name: Deploy to Lambda
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: "us-east-1"
#         run: |
#           terraform init
#           terraform apply -auto-approve
